export default {
  backgroundSound: false,
  requestUserPicture: false,
  requireLandscapeMode: false,
  frameRate: 50,
  gravity: 10,
  gravityScale: 0.009,
  playerYSpeed: 11,
  playerXSpeed: 10,
  playerXSpeedScale: 0.02,
  playerYSpeedScale: 0.006,
  playerFrameRateModifier: 0.6,
  playerScale: 0.3,
  opossumScale: 0.25,
  bubbleSpeedScale: 0.0002,
  leftKeys: ['ArrowLeft', 'SwipeLeft'],
  upKeys: ['ArrowUp', 'SwipeUp'],
  downKeys: ['ArrowDown', 'SwipeDown'],
  rightKeys: ['ArrowRight', 'SwipeRight'],
}
